import React from 'react';

type IUser = {
    "id": number,
    "createdAt": number,
    "updatedAt": number,
    "expoToken": string,
    "fcmToken": string,
    "slugName": string,
    "messagePending": number,
    "type": string,
    "expireContactBook": number,
    "dob": string,
    "code": string,
    "isDeleted": false,
    "phone":string,
    "username": string,
    "name": string,
    "address":string,
    "email": string,
    "gender": string,
    "avatar": string,
    "forgotCode": string,
    "totalNotifyContact": number,
    "totalNotifyNormal": number,
    "parentName": string,
    "parentPhone":string,
    "isChangedDefaultPassword": boolean,
    "updatePasswordAt": number,
    "firstPassword": string,
    "facebookId": string,
    "zaloId": string,
    "googleId": string,
    "appleId": string,
    "school": {
      "id": number,
      "createdAt": number,
      "updatedAt": number,
      "commission": number,
      "email": string,
      "username": string,
      "address": string,
      "name": string,
      "expiredAt": number,
      "updatePasswordAt": number,
      "firstPassword": string,
      "isChangedDefaultPassword": boolean,
      "division": {
        "id": number,
        "createdAt": number,
        "updatedAt": number,
        "commission": number,
        "email": string,
        "username": string,
        "province": string,
        "address": string,
        "name": string,
        "updatePasswordAt": number,
        "firstPassword": string,
        "isChangedDefaultPassword": boolean
      },
      "addressDistrict": {
        "id": number,
        "createdAt": number,
        "updatedAt": number,
        "isBlock": boolean,
        "priority": number,
        "parentCode": string,
        "code": "766",
        "pathWithType": string,
        "path": string,
        "nameWithType": string,
        "type": string,
        "slug": string,
        "name": string,
        "feeDelivery": number
      }
    },
    "classroom": {
      "id"?: number,
      "createdAt"?: number,
      "updatedAt"?: number,
      "name": string,
      "code": string,
      "grade"?: {
        "id": number,
        "createdAt": number,
        "updatedAt": number,
        "name": string
      }
    },
    "totalUnseen": number,
    "teacher": undefined
}

export default IUser